#!/bin/bash -E
set -e
set -o pipefail

BACKUP_MOUNT_PT=/var/backups
BACKUP_PREFIX=${BACKUP_MOUNT_PT}/home-
BACKUP_PREFIX_LEN=$(echo ${BACKUP_PREFIX} |wc -c)

function all_timestamps_with_normalized() {
    ls -d ${BACKUP_PREFIX}* |
    cut -c${BACKUP_PREFIX_LEN}- |
    tr . : |
    xargs -i date -u --date={} "+%FT%T%z {}" |
    tr : .
}

function last_timestamp_with_normalized() {
    (all_timestamps_with_normalized |
    sort -r |
    head -1) || [ $? = 141 ]  # SIGPIPE ok because head closes the pipe early
}

function old_timestamps() {
  OLDFENCE=$(date -u --date='1 week ago' "+%FT%T%z ~" |tr : .)
  (echo $OLDFENCE; all_timestamps_with_normalized) |
  LC_ALL=C sort |
  sed '/ ~$/,$d'
}

if [ ! -v FORCE ]; then
    FENCE_NORMALIZED=$(date -u --date='1 hour ago' "+%FT%T%z" |tr : .)
    LAST_BACKUP_NORMALIZED=$(last_timestamp_with_normalized |cut -d' ' -f1)

    if [[ "${FENCE_NORMALIZED}" < "${LAST_BACKUP_NORMALIZED}" ]]; then
        if [ -v VERBOSE ]; then
            echo "not backing up: a recent backup was made at ${LAST_BACKUP_NORMALIZED}"
        fi
        exit 0
    fi
fi

PREV_TIMESTAMP=$(last_timestamp_with_normalized |cut -d' ' -f2)

lvcreate -l 100%FREE -n home-snapshot -s weessd/home
mount -o ro /dev/mapper/weessd-home--snapshot /mnt/snapshot

TIMESTAMP=$(date +%FT%H.%M%:::z)

function make_backups_readonly() {
    mount -o remount,ro "${BACKUP_MOUNT_PT}"
}
trap make_backups_readonly 1 2 3 15 ERR
mount -o remount,rw "${BACKUP_MOUNT_PT}"

rsync -a --delete \
    --filter=":n .backup-rules" \
    --link-dest="${BACKUP_PREFIX}${PREV_TIMESTAMP}" \
    /mnt/snapshot/ \
    "${BACKUP_PREFIX}${TIMESTAMP}"

old_timestamps |
sort |
sed 's,T[^ ]*,,' |
awk 'BEGIN { prev = "" } $1 == prev { print } { prev = $1 }' |
cut -d' ' -f2 |
xargs -i rm -rf "$BACKUP_PREFIX"{}

make_backups_readonly
trap - 1 2 3 15 ERR

umount /mnt/snapshot
lvremove -f weessd/home-snapshot
